name: Azure Publish

on:
    push:
        branches:
          - jgrant95-patch-1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: innerspacetrainings/azure-npm-publish@v1.0.1
        with:
          npm-email: 'jongrant@corelogic.com'
          organization: 'jgrant95-2'
          feed: 'jgrant95-2'
          username: 'jon grant'
          base64-token: bnRwbXVremJtdXNjMnBkaXBsaXRneWdmdXo1bHdkaGw3czVpNGpvb3liNDZ2NjY2cGZkcQ==
